name: independent_study_gans
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  #  python & pip 
  - conda-forge::python=3.10.13
  - conda-forge::pip=23.3.1
  # pytorch
  - pytorch::pytorch=2.1
  - pytorch::torchvision=0.16
  - pytorch::pytorch-cuda=11.8
  # ml packages
  - conda-forge::pytorch-lightning=2.1
  - conda-forge::einops=0.7.0
  - conda-forge::timm=0.9.8
  - conda-forge::wandb=0.15.12
  # python packages
  - conda-forge::opencv=4.8.1
  - conda-forge::pydantic=2.4.2
  - conda-forge::pydantic-settings=2.0.3
  - conda-forge::pandas=2.1.2
  - conda-forge::typer=0.9.0
  - conda-forge::loguru=0.7.2
  - conda-forge::pytest=7.4.3
  - conda-forge::pytest-mock=3.12.0
  - pip:
    - pytorch-msssim==1.0.*


